In [65]:
import pandas as pd

hi_df = pd.read_csv('err_analysis_clean/hi/predictions.tsv', sep='\t')
hi_trans_df = pd.read_csv('err_analysis_clean/hi_trans/predictions.tsv', sep='\t')
hi_cat_df = pd.read_csv('err_analysis_clean/hi/cat.tsv', sep='\t')

In [67]:
hi_df[['label']]

     label
0        0
1        1
2        0
3        1
4        0
..     ...
993      1
994      0
995      1
996      0
997      1

[998 rows x 1 columns]

In [75]:
both_corr = 0
trans_corr_orig_inco = 0
trans_inco_orig_corr = 0
both_inco = 0
total = 0

for (_, roworig), (_, rowtrans), (_, row_cat) in zip(hi_df.iterrows(), hi_trans_df.iterrows(), hi_cat_df.iterrows()):
    if row_cat['cul']:
        # Access row data using row['column_name'] (.iterrows() suggested by copilot)
        # Perform operations on the row data
        # ...
        both_corr += (roworig['label'] == roworig['pred']) and (rowtrans['label'] == rowtrans['pred'])
        trans_corr_orig_inco += (roworig['label'] != roworig['pred']) and (rowtrans['label'] == rowtrans['pred'])
        trans_inco_orig_corr += (roworig['label'] == roworig['pred']) and (rowtrans['label'] != rowtrans['pred'])
        both_inco += (roworig['label'] != roworig['pred']) and (rowtrans['label'] != rowtrans['pred'])
        total += 1
    
# Create a dataframe with the confusion matrix (unused prompt)
confusion_matrix = pd.DataFrame({
    ("original", 'correct'): [both_corr/total, trans_inco_orig_corr/total],
    ("original", 'incorrect'): [trans_corr_orig_inco/total,both_inco/total],
}, index=[('translate-en', 'correct'), ('translate-en', 'incorrect')])

confusion_matrix.index = pd.MultiIndex.from_tuples(confusion_matrix.index)
confusion_matrix = confusion_matrix.transpose()

confusion_matrix = confusion_matrix.applymap(lambda x: "{:.2f}%".format(x * 100))

confusion_matrix.to_latex(
    buf=f"/Users/chaosarium/Documents/Repos/11711-HW3-Paper/tables/cul.tex", 
    multicolumn_format='c',
    multirow='c',
    escape='latex'
)
confusion_matrix

                   translate-en
                        correct incorrect
original correct         46.74%    20.65%
         incorrect       18.48%    14.13%