In [4]:
import pandas as pd

In [8]:
tab8tsv = pd.read_csv('table8mbert.tsv', delimiter='\t')
tab8tsv

,Language,Zero-Shot Performance (Mean),Zero-Shot Performance (Stdev),Translate-Test (Mean),Translate-Test (Stdev),Cross-Lingual Gap,Concept Shift Gap
0,en_dev,69.812614,1.005138,69.812614,1.005138,0.000000,0.000000
1,hi,50.900000,0.959166,58.316633,2.606495,7.416633,11.495981
2,id,57.039474,0.673309,62.149123,1.306007,5.109649,7.663491
3,jv,53.833333,1.496910,59.833333,0.707107,6.000000,9.979281
4,kn,51.606845,0.618579,56.197830,0.775216,4.590985,13.614785
5,su,52.041667,1.314978,58.166667,2.937623,6.125000,11.645948
6,sw,51.798725,2.109023,62.306642,1.016980,10.507917,7.505972

In [33]:
acc = {}
tab8tsv = pd.read_csv('table8mbert.tsv', delimiter='\t')
for r in tab8tsv.to_dict(orient="records"):
    acc[('mBERTbase', r['Language'])] = {
        'Zero-shot Performance': f"{r['Zero-Shot Performance (Mean)']:#.4} $\pm$ {r['Zero-Shot Performance (Stdev)']:#.4}",
        'Translate-Test': f"{r['Translate-Test (Mean)']:#.4} $\pm$ {r['Translate-Test (Stdev)']:#.4}",
        'Cross-Lingual Transfer Gap': f"{r['Cross-Lingual Gap']:#.4}",
        'Concept Shift Gap': f"{r['Concept Shift Gap']:#.4}",
    }
tab8tsv = pd.read_csv('table8xlmr.tsv', delimiter='\t')
for r in tab8tsv.to_dict(orient="records"):
    acc[('XLM-Rbase', r['Language'])] = {
        'Zero-shot Performance': f"{r['Zero-Shot Performance (Mean)']:#.4} $\pm$ {r['Zero-Shot Performance (Stdev)']:#.4}",
        'Translate-Test': f"{r['Translate-Test (Mean)']:#.4} $\pm$ {r['Translate-Test (Stdev)']:#.4}",
        'Cross-Lingual Transfer Gap': f"{r['Cross-Lingual Gap']:#.4}",
        'Concept Shift Gap': f"{r['Concept Shift Gap']:#.4}",
    }

df = pd.DataFrame.from_dict(acc, orient='index')
# df.index.set_names('Model', level=0, inplace=True)
# df.index.set_names('Language', level=1, inplace=True)
dfs = df.style
def index_formatter(s):
    replacer = {
        'en_dev': 'en$_{dev}$',
        'mBERTbase': 'mBERT\\textsubscript{base}',
        'XLM-Rbase': 'XLM-R\\textsubscript{base}'
    }
    if s in replacer:
        return replacer[s]
    return s
dfs.format_index(index_formatter)
dfs.format_index(lambda s: f"\\textbf{{{s}}}", axis=1)

In [25]:
dfs.to_latex(
    buf=f"/Users/chaosarium/Documents/Repos/11711-HW3-Paper/tables/table8.tex", 
    hrules=True,
    multirow_align='c',
    sparse_index=True,
    # clines=None,
    clines="skip-last;data",
    column_format='l L{0.13\linewidth} L{0.18\linewidth} L{0.16\linewidth} L{0.18\linewidth} L{0.18\linewidth}'
)

---

In [9]:
parsed = { # degenerate
    ('mBERTlarge', 'hi', 2, 'mean'): 50.50200803,
    ('mBERTlarge', 'id', 2, 'mean'): 55.0528169,
    ('mBERTlarge', 'jv', 2, 'mean'): 53.69127517,
    ('mBERTlarge', 'kn', 2, 'mean'): 51.35678392,
    ('mBERTlarge', 'su', 2, 'mean'): 52.14765101,
    ('mBERTlarge', 'sw', 2, 'mean'): 51.93784278,

    ('mBERTlarge', 'hi', 4, 'mean'): 50.50403226,
    ('mBERTlarge', 'id', 4, 'mean'): 55.088339227,
    ('mBERTlarge', 'jv', 4, 'mean'): 53.61486486,
    ('mBERTlarge', 'kn', 4, 'mean'): 51.37815126,
    ('mBERTlarge', 'su', 4, 'mean'): 52.12837838,
    ('mBERTlarge', 'sw', 4, 'mean'): 51.94495413,

    ('mBERTlarge', 'hi', 6, 'mean'): 50.52631579,
    ('mBERTlarge', 'id', 6, 'mean'): 55.07092199,
    ('mBERTlarge', 'jv', 6, 'mean'): 53.53741497,
    ('mBERTlarge', 'kn', 6, 'mean'): 51.43338954,
    ('mBERTlarge', 'su', 6, 'mean'): 52.04081633,
    ('mBERTlarge', 'sw', 6, 'mean'): 51.87845304,

    ('mBERTlarge', 'hi', 8, 'mean'): 50.56910569,
    ('mBERTlarge', 'id', 8, 'mean'): 55.17793594,
    ('mBERTlarge', 'jv', 8, 'mean'): 53.52739726,
    ('mBERTlarge', 'kn', 8, 'mean'): 51.43824027,
    ('mBERTlarge', 'su', 8, 'mean'): 51.98630137,
    ('mBERTlarge', 'sw', 8, 'mean'): 51.84842884,

    ('mBERTlarge', 'hi', 10, 'mean'): 50.51020408,
    ('mBERTlarge', 'id', 10, 'mean'): 55.16071429,
    ('mBERTlarge', 'jv', 10, 'mean'): 53.4137931,
    ('mBERTlarge', 'kn', 10, 'mean'): 51.42614601,
    ('mBERTlarge', 'su', 10, 'mean'): 52.06896552,
    ('mBERTlarge', 'sw', 10, 'mean'): 51.76252319,

    ('mBERTlarge', 'hi', 2, 'delta'): -0.2379919679,
    ('mBERTlarge', 'id', 2, 'delta'): -0.4384111688,
    ('mBERTlarge', 'jv', 2, 'delta'): 0.7579418345,
    ('mBERTlarge', 'kn', 2, 'delta'): -0.0288588183,
    ('mBERTlarge', 'su', 2, 'delta'): 0.68098434,
    ('mBERTlarge', 'sw', 2, 'delta'): 0.9360212852,

    ('mBERTlarge', 'hi', 4, 'delta'): -0.2359677419,
    ('mBERTlarge', 'id', 4, 'delta'): -0.4028888476,
    ('mBERTlarge', 'jv', 4, 'delta'): 0.6815315315,
    ('mBERTlarge', 'kn', 4, 'delta'): -0.007491477392,
    ('mBERTlarge', 'su', 4, 'delta'): 0.6617117117,
    ('mBERTlarge', 'sw', 4, 'delta'): 0.9431326348,

    ('mBERTlarge', 'hi', 6, 'delta'): -0.2136842105,
    ('mBERTlarge', 'id', 6, 'delta'): -0.4203060844,
    ('mBERTlarge', 'jv', 6, 'delta'): 0.6040816327,
    ('mBERTlarge', 'kn', 6, 'delta'): 0.04774680679,
    ('mBERTlarge', 'su', 6, 'delta'): 0.5741496599,
    ('mBERTlarge', 'sw', 6, 'delta'): 0.876631545,

    ('mBERTlarge', 'hi', 8, 'delta'): -0.1708943089,
    ('mBERTlarge', 'id', 8, 'delta'): -0.3132921271,
    ('mBERTlarge', 'jv', 8, 'delta'): 0.5940639269,
    ('mBERTlarge', 'kn', 8, 'delta'): 0.05259753283,
    ('mBERTlarge', 'su', 8, 'delta'): 0.5196347032,
    ('mBERTlarge', 'sw', 8, 'delta'): 0.8466073419,

    ('mBERTlarge', 'hi', 10, 'delta'): -0.2297959184,
    ('mBERTlarge', 'id', 10, 'delta'): -0.3305137845,
    ('mBERTlarge', 'jv', 10, 'delta'): 0.4804597701,
    ('mBERTlarge', 'kn', 10, 'delta'): 0.04050327229,
    ('mBERTlarge', 'su', 10, 'delta'): 0.6022988506,
    ('mBERTlarge', 'sw', 10, 'delta'): 0.7607016975,
}

In [19]:
parsed = { 
    ('mBERTlarge', 'hi', 2, 'mean'): 50.62751004, # actually base...
    ('mBERTlarge', 'id', 2, 'mean'): 56.49207746,
    ('mBERTlarge', 'jv', 2, 'mean'): 54.78187919,
    ('mBERTlarge', 'kn', 2, 'mean'): 51.57035176,
    ('mBERTlarge', 'su', 2, 'mean'): 52.8942953,
    ('mBERTlarge', 'sw', 2, 'mean'): 52.97074954,

    ('mBERTlarge', 'hi', 4, 'mean'): 50.63004032,
    ('mBERTlarge', 'id', 4, 'mean'): 56.51501767,
    ('mBERTlarge', 'jv', 4, 'mean'): 54.6875,
    ('mBERTlarge', 'kn', 4, 'mean'): 51.59663866,
    ('mBERTlarge', 'su', 4, 'mean'): 52.91385135,
    ('mBERTlarge', 'sw', 4, 'mean'): 52.98165138,

    ('mBERTlarge', 'hi', 6, 'mean'): 50.65789474,
    ('mBERTlarge', 'id', 6, 'mean'): 56.47163121,
    ('mBERTlarge', 'jv', 6, 'mean'): 54.59183673,
    ('mBERTlarge', 'kn', 6, 'mean'): 51.62310287,
    ('mBERTlarge', 'su', 6, 'mean'): 52.80612245,
    ('mBERTlarge', 'sw', 6, 'mean'): 52.90055249,

    ('mBERTlarge', 'hi', 8, 'mean'): 50.71138211,
    ('mBERTlarge', 'id', 8, 'mean'): 56.58362989,
    ('mBERTlarge', 'jv', 8, 'mean'): 54.58047945,
    ('mBERTlarge', 'kn', 8, 'mean'): 51.6285956,
    ('mBERTlarge', 'su', 8, 'mean'): 52.73972603,
    ('mBERTlarge', 'sw', 8, 'mean'): 52.88817006,

    ('mBERTlarge', 'hi', 10, 'mean'): 50.66326531,
    ('mBERTlarge', 'id', 10, 'mean'): 56.58482143,
    ('mBERTlarge', 'jv', 10, 'mean'): 54.39655172,
    ('mBERTlarge', 'kn', 10, 'mean'): 51.63412564,
    ('mBERTlarge', 'su', 10, 'mean'): 52.84482759,
    ('mBERTlarge', 'sw', 10, 'mean'): 52.78293135,

    ('mBERTlarge', 'hi', 2, 'delta'): -0.3979919679,
    ('mBERTlarge', 'id', 2, 'delta'): -1.986656783,
    ('mBERTlarge', 'jv', 2, 'delta'): -0.1420581655,
    ('mBERTlarge', 'kn', 2, 'delta'): -0.2500608216,
    ('mBERTlarge', 'su', 2, 'delta'): 0.10598434,
    ('mBERTlarge', 'sw', 2, 'delta'): 0.1391178243,

    ('mBERTlarge', 'hi', 4, 'delta'): -0.3959677419,
    ('mBERTlarge', 'id', 4, 'delta'): -1.951134462,
    ('mBERTlarge', 'jv', 4, 'delta'): -0.2184684685,
    ('mBERTlarge', 'kn', 4, 'delta'): -0.2286934807,
    ('mBERTlarge', 'su', 4, 'delta'): 0.08671171171,
    ('mBERTlarge', 'sw', 4, 'delta'): 0.146229174,

    ('mBERTlarge', 'hi', 6, 'delta'): -0.3736842105,
    ('mBERTlarge', 'id', 6, 'delta'): -1.968551698,
    ('mBERTlarge', 'jv', 6, 'delta'): -0.2959183673,
    ('mBERTlarge', 'kn', 6, 'delta'): -0.1734551965,
    ('mBERTlarge', 'su', 6, 'delta'): -0.0008503401361,
    ('mBERTlarge', 'sw', 6, 'delta'): 0.07972808421,

    ('mBERTlarge', 'hi', 8, 'delta'): -0.3308943089,
    ('mBERTlarge', 'id', 8, 'delta'): -1.861537741,
    ('mBERTlarge', 'jv', 8, 'delta'): -0.3059360731,
    ('mBERTlarge', 'kn', 8, 'delta'): -0.1686044705,
    ('mBERTlarge', 'su', 8, 'delta'): -0.0553652968,
    ('mBERTlarge', 'sw', 8, 'delta'): 0.04970388103,

    ('mBERTlarge', 'hi', 10, 'delta'): -0.3897959184,
    ('mBERTlarge', 'id', 10, 'delta'): -1.878759398,
    ('mBERTlarge', 'jv', 10, 'delta'): -0.4195402299,
    ('mBERTlarge', 'kn', 10, 'delta'): -0.180698731,
    ('mBERTlarge', 'su', 10, 'delta'): 0.02729885057,
    ('mBERTlarge', 'sw', 10, 'delta'): -0.03620176337,
    
    # ====
    
    ('xlmrbase', 'hi', 2, 'mean'): 62.4497992,
    ('xlmrbase', 'id', 2, 'mean'): 68.96126761,
    ('xlmrbase', 'jv', 2, 'mean'): 53.9261745,
    ('xlmrbase', 'kn', 2, 'mean'): 53.35008375,
    ('xlmrbase', 'su', 2, 'mean'): 53.55704698,
    ('xlmrbase', 'sw', 2, 'mean'): 52.6691042,

    ('xlmrbase', 'hi', 4, 'mean'): 62.45967742,
    ('xlmrbase', 'id', 4, 'mean'): 68.93992933,
    ('xlmrbase', 'jv', 4, 'mean'): 53.88513514,
    ('xlmrbase', 'kn', 4, 'mean'): 53.41176471,
    ('xlmrbase', 'su', 4, 'mean'): 53.51351351,
    ('xlmrbase', 'sw', 4, 'mean'): 52.62385321,

    ('xlmrbase', 'hi', 6, 'mean'): 62.44939271,
    ('xlmrbase', 'id', 6, 'mean'): 68.91843972,
    ('xlmrbase', 'jv', 6, 'mean'): 54.14965986,
    ('xlmrbase', 'kn', 6, 'mean'): 53.35581788,
    ('xlmrbase', 'su', 6, 'mean'): 53.53741497,
    ('xlmrbase', 'sw', 6, 'mean'): 52.67034991,

    ('xlmrbase', 'hi', 8, 'mean'): 62.5203252,
    ('xlmrbase', 'id', 8, 'mean'): 68.87900356,
    ('xlmrbase', 'jv', 8, 'mean'): 54.28082192,
    ('xlmrbase', 'kn', 8, 'mean'): 53.28257191,
    ('xlmrbase', 'su', 8, 'mean'): 53.56164384,
    ('xlmrbase', 'sw', 8, 'mean'): 52.68022181,

    ('xlmrbase', 'hi', 10, 'mean'): 62.40816327,
    ('xlmrbase', 'id', 10, 'mean'): 68.82142857,
    ('xlmrbase', 'jv', 10, 'mean'): 54.24137931,
    ('xlmrbase', 'kn', 10, 'mean'): 53.3106961,
    ('xlmrbase', 'su', 10, 'mean'): 53.48275862,
    ('xlmrbase', 'sw', 10, 'mean'): 52.56029685,

    ('xlmrbase', 'hi', 2, 'delta'): -0.01020080321,
    ('xlmrbase', 'id', 2, 'delta'): -0.108907833,
    ('xlmrbase', 'jv', 2, 'delta'): -0.007158836689,
    ('xlmrbase', 'kn', 2, 'delta'): -0.03889788397,
    ('xlmrbase', 'su', 2, 'delta'): 0.1237136465,
    ('xlmrbase', 'sw', 2, 'delta'): 0.009723512586,

    ('xlmrbase', 'hi', 4, 'delta'): -0.0003225806452,
    ('xlmrbase', 'id', 4, 'delta'): -0.13024611,
    ('xlmrbase', 'jv', 4, 'delta'): -0.0481981982,
    ('xlmrbase', 'kn', 4, 'delta'): 0.02278306982,
    ('xlmrbase', 'su', 4, 'delta'): 0.08018018018,
    ('xlmrbase', 'sw', 4, 'delta'): -0.03552748116,

    ('xlmrbase', 'hi', 6, 'delta'): -0.01060728745,
    ('xlmrbase', 'id', 6, 'delta'): -0.1517357223,
    ('xlmrbase', 'jv', 6, 'delta'): 0.2163265306,
    ('xlmrbase', 'kn', 6, 'delta'): -0.03316376085,
    ('xlmrbase', 'su', 6, 'delta'): 0.1040816327,
    ('xlmrbase', 'sw', 6, 'delta'): 0.01096921575,

    ('xlmrbase', 'hi', 8, 'delta'): 0.06032520325,
    ('xlmrbase', 'id', 8, 'delta'): -0.1911718799,
    ('xlmrbase', 'jv', 8, 'delta'): 0.3474885845,
    ('xlmrbase', 'kn', 8, 'delta'): -0.106409724,
    ('xlmrbase', 'su', 8, 'delta'): 0.1283105023,
    ('xlmrbase', 'sw', 8, 'delta'): 0.02084111929,

    ('xlmrbase', 'hi', 10, 'delta'): -0.05183673469,
    ('xlmrbase', 'id', 10, 'delta'): -0.2487468672,
    ('xlmrbase', 'jv', 10, 'delta'): 0.308045977,
    ('xlmrbase', 'kn', 10, 'delta'): -0.07828554098,
    ('xlmrbase', 'su', 10, 'delta'): 0.04942528736,
    ('xlmrbase', 'sw', 10, 'delta'): -0.09908384616,
}

In [22]:
data = {}
for lang in ['hi', 'id', 'jv', 'kn', 'su', 'sw']:
    data[('mBERTlarge', lang)] = {}
    for k in [2,4,6,8,10]:
        data[('mBERTlarge', lang)][(k, 'mean')] = parsed[('mBERTlarge', lang, k, 'mean')]
        data[('mBERTlarge', lang)][(k, 'delta')] = parsed[('mBERTlarge', lang, k, 'delta')]
for lang in ['hi', 'id', 'jv', 'kn', 'su', 'sw']:
    data[('xlmrbase', lang)] = {}
    for k in [2,4,6,8,10]:
        data[('xlmrbase', lang)][(k, 'mean')] = parsed[('xlmrbase', lang, k, 'mean')]
        data[('xlmrbase', lang)][(k, 'delta')] = parsed[('xlmrbase', lang, k, 'delta')]

In [24]:
df = pd.DataFrame.from_dict(data, orient='index')
dfs = df.style

dfs.format_index(lambda s: f"$k = {s}$", axis=1, level=0)
dfs.format_index(lambda s: s.replace("delta", "$\\Delta$").replace("mean", "Score"), axis=1, level=1)
dfs.format_index(lambda s: s.replace("mBERTlarge", 'mBERT\\textsubscript{base}').replace("xlmrbase", 'XLM-R\\textsubscript{base}'), axis=0, level=0)
dfs.format("{:.2f}")
dfs

In [25]:
dfs.to_latex(
    buf=f"/Users/chaosarium/Documents/Repos/11711-HW3-Paper/tables/table13.tex", 
    hrules=True,
    multirow_align='c',
    multicol_align='c',
    sparse_index=True,
    # clines=None,
    clines="skip-last;data",
)